import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SearchProvider } from '@/app/components/Search/Search'
import './globals.css'

import Header from "@/app/components/Structure/Header/Header"
import Footer from "@/app/components/Structure/Footer/Footer"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body>
    <Header />

    <main className="layout">
      <SearchProvider>
        {children}
      </SearchProvider>
    </main>

    <Footer />
  </body>
</html>
  );
}
