import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

//Import of Providers
import { AuthProvider } from "@/context/Auth";
import { SearchProvider } from "@/context/Search"

import "./globals.css";

import Header from "@/app/components/Structure/Header/Header";
import Footer from "@/app/components/Structure/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <SearchProvider>
            <div className="app">
              <Header />

              <main className="main">
                {children}
              </main>

              <Footer />
            </div>
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}